name: Another workflow

on: [push,pull_request]

jobs:
  deploy:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Publish to surge.sh
        uses: dswistowski/surge-sh-action@v1.0.0
        with:
          suffix: 'my-'
          prefix: '-storybook'
          action: 'publish'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
