name: My workflow

on: [push,pull_request] 

jobs:
  deploy:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to foo-bar.surge.sh
        uses: itaditya/surge-action@v1
        with:
          suffix: 'my-'
          prefix: '-storybook'
          action: 'publish'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
